sdm660: scsi: Add missing boolean argument
../drivers/scsi/ufs/ufshcd.c:3112:3: error: too few arguments to function 'ufshcd_release'
   ufshcd_release(hba);
   ^
../drivers/scsi/ufs/ufshcd.c:1655:6: note: declared here
 void ufshcd_release(struct ufs_hba *hba, bool no_sched)
      ^

Signed-off-by: ultron14 <ultron1704@gmail.com>